config/routes.rb
Closedfiles::Application.routes.draw do

  get "main/index"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

#  match "/closedfiles/index.js", :controller => 'closedfiles', :action => 'index', :format => :js

  resources :sessions
  resources :users
  resources :password_resets
  resources :searches
  
  root to: 'main#index'
  resources :closedfiles

end

app/models/closedfile.rb
class Closedfile < ActiveRecord::Base
  attr_accessible :atty_name, :box_number, :client_name, :cm_number, :destruction_date, :file_number, :matter_name, :scaned, :wallet_qty
  def self.search(search)
    if search
      where('file_number LIKE ? OR client_name LIKE ? OR matter_name LIKE ? OR atty_name LIKE ? OR cm_number LIKE?', "%#{search}%","%#{search}%", "%#{search}%","%#{search}%", "%#{search}%")
    else
      scoped
    end
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create
  before_create { generate_token(:auth_token) }
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  def current_user
    @current_user ||= User.find_by_auth_token( cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user
  
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/closedfiles_controller.rb
class ClosedfilesController < ApplicationController
  # GET /closedfiles
  # GET /closedfiles.json
  
  before_filter :authorize, only: [:edit, :update]  
  helper_method :sort_column, :sort_direction
  def index
    @closedfiles = Closedfile.all
    @closedfiles = Closedfile.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 50, :page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @closedfiles }
      format.js # index.js.erb
    end
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end
  
  private
  def sort_column
    params[:sort] || "file_number"
  end
  
  def sort_direction
    params[:direction] || "asc"
  end
  
  # GET /closedfiles/1
  # GET /closedfiles/1.json
  def show
    @closedfile = Closedfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @closedfile }
    end
  end

  # GET /closedfiles/new
  # GET /closedfiles/new.json
  def new
    @closedfile = Closedfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @closedfile }
    end
  end

  # GET /closedfiles/1/edit
  def edit
    @closedfile = Closedfile.find(params[:id])
  end

  # POST /closedfiles
  # POST /closedfiles.json
  def create
    @closedfile = Closedfile.new(params[:closedfile])

    respond_to do |format|
      if @closedfile.save
        format.html { redirect_to @closedfile, notice: 'Closedfile was successfully created.' }
        format.json { render json: @closedfile, status: :created, location: @closedfile }
      else
        format.html { render action: "new" }
        format.json { render json: @closedfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /closedfiles/1
  # PUT /closedfiles/1.json
  def update
    @closedfile = Closedfile.find(params[:id])

    respond_to do |format|
      if @closedfile.update_attributes(params[:closedfile])
        format.html { redirect_to @closedfile, notice: 'Closedfile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @closedfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /closedfiles/1
  # DELETE /closedfiles/1.json
  def destroy
    @closedfile = Closedfile.find(params[:id])
    @closedfile.destroy

    respond_to do |format|
      format.html { redirect_to closedfiles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => "Email sent with password reset instructions."
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password &crarr; 
        reset has expired."
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Password has been reset."
    else
      render :edit
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        cookies.permanent[:auth_token] = user.auth_token
      else
        cookies[:auth_token] = user.auth_token  
      end
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    cookies.delete(:auth_token)
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end

end

app/helpers/closedfiles_helper.rb
module ClosedfilesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/closedfiles/_closedfile.html.erb
<div class="product">
  <h2><%= link_to closedfile.file_number, closedfile %></h2>
  <div class="details">
<p>
  <strong>File Number:</strong><br>
  <%= @closedfile.file_number %>
</p>
<p>
  <strong>Box Number:</strong><br>
  <%= @closedfile.box_number %>
</p>
<p>
  <strong>No. of Wallets:</strong><br>
  <%= @closedfile.wallet_qty %>
</p>
<p>
  <strong>Client Name:</strong><br>
  <%= @closedfile.client_name %>
</p>
<p>
  <strong>Matter Name:</strong><br>
  <%= @closedfile.matter_name %>
</p>
<p>
  <strong>Client Matter Number:</strong><br>
  <%= @closedfile.cm_number %>
</p>
<p>
  <strong>Attorney Name:</strong><br>
  <%= @closedfile.atty_name %>
</p>
<p>
  <strong>Destruction Date:</strong><br>
  <%= @closedfile.destruction_date %>
</p>
<p>
  <strong>Scanned?:</strong><br>
  <%= @closedfile.scaned %>
</p>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              closedfiles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_closedfile_path(@closedfile), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              closedfile_path(@closedfile),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>
  </div>
</div>

app/views/closedfiles/_closedfiles.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "file_number", "File #" =%></th>
      <th><%= sortable "box_number", "Box #" =%></th>
      <th><%= sortable "wallet_qty", "No. of Wallets" =%></th>
      <th><%= sortable "client_name", "Client Name" =%></th>
      <th><%= sortable "matter_name", "Matter Name" =%></th>
      <th><%= sortable "cm_number", "Client Matter #" =%></th>
      <th><%= sortable "atty_name", "Attorney Name"=%></th>
      <th><%= sortable "destruction_date", "Destruction Date" =%></th>
      <th><%= sortable "scanned", "Scanned?" =%></th>
      <% if current_user %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% else %>
      
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @closedfiles.each do |closedfile| %>
      <tr>
        <td><%= link_to closedfile.file_number, closedfile_path(closedfile) %></td>
        <td><%= closedfile.box_number %></td>        
        <td><%= closedfile.wallet_qty %></td>
        <td><span class="client_name"><%= closedfile.client_name %></span></td>
        <td><span class="matter_name"><%= closedfile.matter_name %></span></td>
        <td><%= closedfile.cm_number %></td>
        <td><%= closedfile.atty_name %></td>
        <td><%= closedfile.destruction_date %></td>
        <td><%= closedfile.scaned? ? 'Yes' : 'No' %></td>
        <% if current_user %>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_closedfile_path(closedfile), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      closedfile_path(closedfile),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        <% else %>
        
        <% end %>                      
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/closedfiles/_form.html.erb
<%= simple_form_for @closedfile, :html => { :class => 'form-horizontal' } do |f| %>
<fieldset>
  <legend><%= controller.action_name.capitalize %> File</legend>
  
  <%= f.input :file_number, :label => 'File Number' %>
  <%= f.input :box_number, :label => 'Box Number' %>
  <%= f.input :wallet_qty, :label => 'No. of Wallets' %>
  <%= f.input :client_name, :label => 'Client Name' %>
  <%= f.input :matter_name, :label => 'Matter Name' %>
  <%= f.input :cm_number, :label => 'Client/Matter #' %>
  <%= f.input :atty_name, :label => 'Attorney Name' %>
  <%= f.input :destruction_date, :label => 'Destruction Date' %>
  <%= f.input :scaned %>

  <div class="form-actions">
    <%= f.submit 'Save', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                closedfiles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/closedfiles/edit.html.erb
<%- model_class = @closedfile.class -%>

<%= render :partial => 'form' %>

app/views/closedfiles/index.html.erb
<%- model_class = Closedfile.new.class -%>
<h1>Closed Files</h1>
<%= form_tag closedfiles_path, :method => 'get', :id => "closedfiles_search" do %>
    <%= text_field_tag :search, params[:search], :class => 'search-query' %>
    <%= submit_tag "Search", :name => nil, :class => 'btn' %>

<% end %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_closedfile_path,
            :class => 'btn btn-primary new' %>
<div id="closedfiles">
  <%= render 'closedfiles' %>
</div>

<%= will_paginate @products %>

app/views/closedfiles/index.js.erb
$('#closedfiles').html('<%= escape_javascript(render :partial => ("closedfiles")) %>');

app/views/closedfiles/new.html.erb
<%- model_class = @closedfile.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/closedfiles/show.html.erb
<%- model_class = @closedfile.class -%>
<h1><%= @closedfile.file_number %></h1>

<p>
  <strong>File Number:</strong><br>
  <%= @closedfile.file_number %>
</p>
<p>
  <strong>Box Number:</strong><br>
  <%= @closedfile.box_number %>
</p>
<p>
  <strong>No. of Wallets:</strong><br>
  <%= @closedfile.wallet_qty %>
</p>
<p>
  <strong>Client Name:</strong><br>
  <%= @closedfile.client_name %>
</p>
<p>
  <strong>Matter Name:</strong><br>
  <%= @closedfile.matter_name %>
</p>
<p>
  <strong>Client Matter Number:</strong><br>
  <%= @closedfile.cm_number %>
</p>
<p>
  <strong>Attorney Name:</strong><br>
  <%= @closedfile.atty_name %>
</p>
<p>
  <strong>Destruction Date:</strong><br>
  <%= @closedfile.destruction_date %>
</p>
<p>
  <strong>Scanned?:</strong><br>
  <%= @closedfile.scaned %>
</p>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              closedfiles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_closedfile_path(@closedfile), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              closedfile_path(@closedfile),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Closed Files</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Carlile Patchen &amp; Murphy</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <% if current_user %>
              <p class="navbar-text pull-right">Logged in as <%= current_user.email %>. <%= link_to "Log Out", session_path("current"), method: "delete" %></p>
            <% else %>
              <p class="navbar-text pull-right"><%= link_to "Sign Up", new_user_path %> or <%= link_to "Log In", new_session_path %></p>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<div class="main container-fluid">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">X</a>
      <%= msg  %>
    </div>
  <% end %>	
	<%= yield %>
</div>
</body>
</html>

app/views/main/index.html.erb
<div id="container">Loading...</div>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>